version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.19.2
    ports:
      - '9090:9090'
    volumes:
      - ./config:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--storage.tsdb.path=/prometheus'

  node-1:
    image: prom/node-exporter:v1.0.1
    ports:
      - '8080:9100'
  node-2:
    image: prom/node-exporter:v1.0.1
    ports:
      - '8081:9100'
  node-3:
    image: prom/node-exporter:v1.0.1
    ports:
      - '8082:9100'

volumes:
  prometheus-data: {}